# Generated by Django 4.2.5 on 2024-09-02 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comunidad', '0001_initial'),
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_Entrada', models.AutoField(primary_key=True, serialize=False, verbose_name='Entrada')),
                ('Remito', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Remito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('id_Proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comunidad.proveedor', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id_Salida', models.AutoField(primary_key=True, serialize=False, verbose_name='Salida')),
                ('recetas', models.CharField(max_length=100, verbose_name='Receta')),
                ('duplicado', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Duplicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Entregado')),
                ('id_Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comunidad.paciente')),
                ('id_Proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comunidad.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movimientos.salida')),
            ],
        ),
        migrations.AddField(
            model_name='salida',
            name='productos',
            field=models.ManyToManyField(through='Movimientos.SalidaProducto', to='Productos.producto'),
        ),
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Caducidad', models.DateField(verbose_name='Fecha de caducidad')),
                ('cantidad', models.PositiveIntegerField()),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movimientos.entrada')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='productos',
            field=models.ManyToManyField(through='Movimientos.EntradaProducto', to='Productos.producto'),
        ),
    ]
