# Generated by Django 4.2.5 on 2024-09-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='id_Entrada',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Número de movimiento'),
        ),
    ]
