# Generated by Django 4.2.5 on 2024-09-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0009_alter_laboratorio_id_contacto_and_more'),
        ('Movimientos', '0003_remove_salida_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='id_Entrada',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código de movimiento'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='id_Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comunidad.paciente', verbose_name='Nombre del paciente'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='id_Salida',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código de movimiento'),
        ),
    ]
