# Generated by Django 4.2.4 on 2024-09-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0004_alter_entrada_id_entrada_alter_salida_id_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='is_active',
        ),
        migrations.AddField(
            model_name='salida',
            name='en_espera',
            field=models.BooleanField(default=True, verbose_name='En Espera'),
        ),
        migrations.AddField(
            model_name='salida',
            name='entregado',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
    ]
