# Generated by Django 4.2.5 on 2024-10-02 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_producto_stock'),
        ('Movimientos', '0005_remove_salida_is_active_salida_en_espera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mov', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=7, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='salida',
            name='en_espera',
        ),
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('id_ajuste', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de movimiento')),
                ('motivo', models.CharField(max_length=150, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('productos', models.ManyToManyField(through='Movimientos.AjusteProducto', to='Productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='ajusteproducto',
            name='ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movimientos.ajustestock'),
        ),
        migrations.AddField(
            model_name='ajusteproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto'),
        ),
    ]
