# Generated by Django 4.2.5 on 2024-10-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0006_ajusteproducto_remove_salida_en_espera_ajustestock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajustestock',
            options={'verbose_name': 'Ajuste de stock', 'verbose_name_plural': 'Ajustes de stock'},
        ),
    ]
