# Generated by Django 4.2.5 on 2024-10-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0009_remove_historialmovimiento_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusteproducto',
            name='ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Movimientos.ajustestock'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Movimientos.entrada'),
        ),
        migrations.AlterField(
            model_name='historialproductos',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Movimientos.historialmovimiento'),
        ),
        migrations.AlterField(
            model_name='salidaproducto',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Movimientos.salida'),
        ),
    ]
