# Generated by Django 4.2.4 on 2024-11-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0010_alter_ajusteproducto_ajuste_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajusteproducto',
            options={'verbose_name': 'Detalle de productos', 'verbose_name_plural': 'Detalles de productos'},
        ),
        migrations.AlterModelOptions(
            name='entradaproducto',
            options={'verbose_name': 'Detalle de productos', 'verbose_name_plural': 'Detalles de productos'},
        ),
        migrations.AlterModelOptions(
            name='salidaproducto',
            options={'verbose_name': 'Detalle de productos', 'verbose_name_plural': 'Detalles de productos'},
        ),
    ]
