# Generated by Django 5.0.3 on 2024-09-07 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id_Provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='localidades',
            fields=[
                ('id_Localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('Id_provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comunidad.provincia')),
            ],
        ),
    ]
