# Generated by Django 5.0.3 on 2024-09-09 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0002_provincia_localidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comunidad.localidades'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comunidad.provincia'),
        ),
    ]
