# Generated by Django 4.2.5 on 2024-09-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0003_alter_contacto_localidad_alter_contacto_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='departamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Comunidad.localidades'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='piso',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Piso'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Comunidad.provincia'),
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('nombre', 'r_Social')},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='correo',
        ),
    ]
