# Generated by Django 4.2.5 on 2024-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0005_alter_contacto_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.CharField(max_length=50, verbose_name='email'),
        ),
    ]
