# Generated by Django 4.2.5 on 2024-09-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0006_alter_contacto_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_Opcional',
            field=models.IntegerField(null=True, verbose_name='Numero alternativo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_Telefono',
            field=models.IntegerField(null=True, verbose_name='Número telefónico'),
        ),
    ]
