# Generated by Django 4.2.5 on 2024-09-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0007_alter_contacto_email_alter_contacto_numero_opcional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='numero_Opcional',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero alternativo'),
        ),
    ]
