# Generated by Django 4.2.5 on 2024-09-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0008_alter_contacto_numero_opcional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='id_Contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comunidad.contacto', verbose_name='Información de contacto'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_Contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comunidad.contacto', verbose_name='Información de contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_Contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comunidad.contacto', verbose_name='Información de contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='r_Social',
            field=models.CharField(choices=[('SA', 'Sociedad Anónima'), ('SRL', 'Sociedad de Responsabilidad Limitada'), ('SAS', 'Sociedad por Acciones Simplificada'), ('Cooperativa', 'Cooperativa'), ('Monotributista', 'Monotributista'), ('Autónomo', 'Autónomo')], max_length=50, verbose_name='Razón Social'),
        ),
    ]
