# Generated by Django 4.2.5 on 2024-10-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0011_remove_laboratorio_id_contacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='localidades',
            new_name='localidad',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='trabajo',
            field=models.CharField(choices=[('auxiliar', 'Auxiliar'), ('administrativo', 'Administrativo'), ('farmacéutico', 'Farmacéutico'), ('médico', 'médico')], max_length=20, verbose_name='Puesto'),
        ),
    ]
