# Generated by Django 4.2.4 on 2024-10-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0013_alter_localidad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Comunidad.localidad'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_Contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Comunidad.contacto'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='Id_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Comunidad.provincia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_Contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comunidad.contacto', verbose_name='Información de contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_Contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comunidad.contacto', verbose_name='Información de contacto'),
        ),
    ]
