# Generated by Django 4.2.5 on 2024-10-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0015_alter_empleado_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='calle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='código_Postal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Codigo Postal'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Comunidad.localidad'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_Telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número telefónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='número',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='trabajo',
            field=models.CharField(choices=[('psiquiatra', 'Psiquiatra'), ('administrativo', 'Administrativo'), ('doctor', 'Doctor')], max_length=20, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_Contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Comunidad.contacto', verbose_name='Información de contacto'),
        ),
    ]
