# Generated by Django 4.2.4 on 2024-10-28 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0017_puesto_alter_empleado_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Comunidad.puesto', verbose_name='Puesto'),
        ),
    ]
