# Generated by Django 4.2.5 on 2024-09-02 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comunidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Comercial', models.CharField(max_length=17, verbose_name='Nombre')),
                ('principio_activo', models.CharField(max_length=17, verbose_name='Droga')),
                ('presentacion', models.CharField(max_length=17, verbose_name='Presentacion')),
                ('tipo_Producto', models.CharField(choices=[('venta libre', 'Venta Libre'), ('bajo receta', 'Bajo Receta'), ('bajo receta duplicada', 'Bajo receta duplicado-Lista IV')], max_length=45, verbose_name='Tipo de producto')),
                ('accion_farma', models.CharField(max_length=17, verbose_name='Acción')),
                ('id_Laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comunidad.laboratorio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Medicamentos',
                'unique_together': {('nombre_Comercial', 'principio_activo', 'presentacion')},
            },
        ),
    ]
