# Generated by Django 4.2.5 on 2024-09-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0008_alter_contacto_numero_opcional'),
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_Laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comunidad.laboratorio', verbose_name='Laboratorio'),
        ),
    ]
