# Generated by Django 5.1.1 on 2024-09-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_producto_id_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
