# Generated by Django 4.2.5 on 2024-10-09 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_droga',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad de la droga activa', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='forma_farmaceutica',
            field=models.CharField(help_text='Ejemplo: comprimido, jarabe, inyectable', max_length=100, null=True, verbose_name='Forma farmacéutica'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('mcg', 'Microgramo(s) (mcg)'), ('mg', 'Miligramo(s) (mg)'), ('g', 'Gramo(s) (g)')], help_text='Seleccione la unidad de medida apropiada', max_length=10, null=True, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='accion_farma',
            field=models.CharField(max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_Comercial',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(help_text='Ejemplo: Caja x 30 comprimidos', max_length=200, null=True, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='principio_activo',
            field=models.CharField(max_length=50, verbose_name='Droga'),
        ),
    ]
