# Generated by Django 4.2.4 on 2024-10-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_alter_producto_id_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.IntegerField(blank=True, help_text='Ejemplo: 30 comprimidos', null=True, verbose_name='Presentación'),
        ),
    ]
