# Generated by Django 4.2.5 on 2024-10-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_producto_cantidad_droga_secundario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Droga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='DrogaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('medida', models.CharField(choices=[('g', 'G'), ('mg', 'Mg')], max_length=20, verbose_name='Unidad de medida')),
                ('id_droga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.droga')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_droga',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_droga_secundario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='principio_activo_secundario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='principio_activo',
        ),
        migrations.AddField(
            model_name='producto',
            name='principio_activo',
            field=models.ManyToManyField(through='Productos.DrogaProducto', to='Productos.droga'),
        ),
    ]
