# Generated by Django 4.2.5 on 2024-10-24 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0009_accionfarma_alter_drogaproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='accion_farma',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='Productos.accionfarma', verbose_name='Acción Farmacológica'),
        ),
    ]
