# Generated by Django 4.2.4 on 2024-11-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0010_alter_producto_accion_farma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='forma_farmaceutica',
            field=models.CharField(choices=[('1', 'Comprimidos'), ('2', 'Cápsulas'), ('3', 'Grageas'), ('4', 'Jarabe'), ('5', 'Suspensión'), ('6', 'Emulsión'), ('7', 'Polvos'), ('8', 'Ungüento'), ('9', 'Crema'), ('10', 'Gel'), ('11', 'Pomada'), ('12', 'Inhalador'), ('13', 'Aerosol'), ('14', 'Solución'), ('15', 'Gotas'), ('16', 'Parche transdérmico'), ('17', 'Supositorio'), ('18', 'Óvulo'), ('19', 'Ampolla'), ('20', 'Vial'), ('21', 'Implante'), ('22', 'Tableta masticable'), ('23', 'Sublingual'), ('24', 'Enema'), ('25', 'Granulado'), ('26', 'Espuma'), ('27', 'Microgránulos'), ('28', 'Liposoma'), ('29', 'Microesfera'), ('30', 'Nanosuspensión'), ('31', 'Nanopartícula'), ('32', 'Solución oftálmica'), ('33', 'Solución ótica'), ('34', 'Jabón medicinal'), ('35', 'Polvo para inyección'), ('36', 'Polvo para suspensión'), ('37', 'Infusión'), ('38', 'Elixir'), ('39', 'Linimento'), ('40', 'Pastillas para chupar'), ('41', 'Polvo efervescente'), ('42', 'Liofilizado para inyección'), ('43', 'Liofilizado para inhalación'), ('44', 'Emplasto'), ('45', 'Parches oculares'), ('46', 'Pellets'), ('47', 'Comprimidos recubiertos'), ('48', 'Cápsulas de liberación modificada'), ('49', 'Sistema de liberación controlada'), ('50', 'Nanopartículas activas'), ('51', 'Células madre'), ('52', 'Vectores virales'), ('53', 'Tejidos de ingeniería'), ('54', 'Comprimidos orodispersables'), ('55', 'Aerosol nasal'), ('56', 'Implantes subcutáneos'), ('57', 'Inyectables de depósito'), ('58', 'Polvo para reconstitución'), ('59', 'Otros')], help_text='Ejemplo: comprimido, jarabe, inyectable', max_length=100, null=True, verbose_name='Forma farmacéutica'),
        ),
    ]
